# Generated by Django 4.0 on 2024-05-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cstackuser",
            name="entry_era",
        ),
        migrations.AddField(
            model_name="cstackuser",
            name="collection",
            field=models.ManyToManyField(
                blank=True, related_name="users_collection", to="cards.Card"
            ),
        ),
        migrations.AlterField(
            model_name="cstackuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bias", models.CharField(max_length=60)),
                ("entry_era", models.TextField(blank=True, verbose_name="entry era")),
                ("collection", models.TextField(blank=True)),
                ("fav_cards", models.TextField(blank=True)),
                (
                    "exp_card",
                    models.CharField(
                        max_length=60, verbose_name="the most expensive card"
                    ),
                ),
                (
                    "des_card",
                    models.CharField(
                        max_length=60, verbose_name="the most desirable card"
                    ),
                ),
                ("about", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="myauth.cstackuser",
                    ),
                ),
            ],
        ),
    ]
