# Generated by Django 4.0 on 2024-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_profile_image_remove_profile_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collection',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='user', max_length=60),
        ),
    ]
