# Generated by Django 4.0 on 2024-05-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('myauth', '0004_remove_profile_collection_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstackuser',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='users', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entry_era',
            field=models.CharField(blank=True, max_length=60, verbose_name='entry era'),
        ),
    ]
