# Generated by Django 4.0 on 2024-05-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_alter_cstackuser_collection_alter_profile_entry_era'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bias',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='des_card',
            field=models.CharField(blank=True, max_length=60, verbose_name='the most desirable card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp_card',
            field=models.CharField(blank=True, max_length=60, verbose_name='the most expensive card'),
        ),
    ]
